
#include "Items.h"

const std::array<const char*, 1780> ItemNames = {
	"None",
	"Herb",
	"Potion",
	"Mega Potion",
	"Lifesoot",
	"Lifepowder",
	"Dust of Life",
	"Max Potion",
	"Ancient Potion",
	"Immunizer",
	"Antidote Herb",
	"Antidote",
	"Aloe Leaf",
	"Burn Ointment",
	"Anesfreesia",
	"Paracare",
	"Hot Pepper",
	"Energy Drink",
	"Girthy Garlic",
	"Zest Pill",
	"Soapgrass",
	"Soap Scud",
	"Vital Essence",
	"Unknown",
	"Manyberry",
	"Intuitizer",
	"Nulberry Elixir",
	"Cool Mist",
	"Hot Mist",
	"Mahana Dunker",
	"Unknown",
	"Rutoh Ringer",
	"Kuan Cruller",
	"Lulu Donut",
	"Unknown",
	"Unknown",
	"Nua Te Fritter",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Whetstone",
	"Super Whetstone",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Surrogate Gem",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Flash Bomb",
	"Sonic Bomb",
	"Poison Knife",
	"Paralysis Knife",
	"Sleep Knife",
	"Throwing Knife",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Stone",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Paintball",
	"Unknown",
	"Unknown",
	"Pitfall Trap",
	"Shock Trap",
	"Tranq Trap",
	"Big Barrel Bomb",
	"Power Paintball",
	"Mega Barrel Bomb",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Vitality Nutriment",
	"Strength Nutriment",
	"Defense Nutriment",
	"Drawbridge Lever",
	"Felyne Barrel Bomb",
	"Terga Nitroshroom",
	"Unknown",
	"Recognition Letter",
	"Commendation",
	"Bumblepumpkin",
	"Bronze Ticket",
	"Silver Ticket",
	"Gold Ticket",
	"Platinum Ticket",
	"Armor Sphere S",
	"Unknown",
	"Unknown",
	"Well-Done Steak",
	"Muscle Meat",
	"Toughness Meat",
	"Quickness Meat",
	"Gourmet Steak",
	"Unknown",
	"Stable Blueprint 1",
	"Stable Blueprint 2",
	"Stable Blueprint 3",
	"Stable Blueprint 4",
	"Stable Blueprint 5",
	"Stable Blueprint 6",
	"Expedition+ Ticket",
	"Silver Exped.+ Ticket",
	"Gold Exped.+ Ticket",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Herbivore Stimulant",
	"Bird Wyv. Stimulant",
	"Flying Wyv. Stimulant",
	"Fanged Beast Stimulant",
	"Brute Wyv. Stimulant",
	"Fanged Wyv. Stimulant",
	"Leviathan Stimulant",
	"Temnoceran Stimulant",
	"Amphibian Stimulant",
	"Eld. Dragon Stimulant",
	"Psc. Wyv. Stimulant",
	"Universal Stimulant",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Training Charm",
	"Unknown",
	"Gathering Charm",
	"Lucky Charm",
	"Finding Charm",
	"Mounting Charm",
	"Selling Charm",
	"Buying Charm",
	"Adamant Charm",
	"Might Charm",
	"Recovery Charm",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Aged Felvine",
	"Felvine Coin",
	"Unique Mushroom",
	"Golden Fragment",
	"Goldenfry",
	"Unknown",
	"Unknown",
	"Brocadefish",
	"Ancient Beans",
	"Royal Honey",
	"Crimson Coral",
	"Tropical Berry",
	"Crystal Bone",
	"King Cactus",
	"Silver Spidersilk",
	"Pittance Fang",
	"Royal Rhino",
	"Coal",
	"Golden Bone",
	"Volcanic Pepper",
	"Divine Rhino",
	"Great Shroom",
	"Goldenfish",
	"Diamond Dust",
	"Aurora Grass",
	"Icebound Bone",
	"Golden Chunk",
	"Choice Mushroom",
	"Gold Cricket",
	"Ancient Coin",
	"Balmstone Chunk",
	"Century Walnut",
	"Silver Cricket",
	"Black Pearl",
	"Bottle Cap",
	"Grand Felvine",
	"Valuable Scale",
	"Mazewalker's Seal",
	"Fortune Fang",
	"Fortune Scale",
	"Goldmine Fang",
	"Goldmine Scale",
	"Felvine Bud",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Trap Tool",
	"Unknown",
	"Unknown",
	"Unknown",
	"Large Barrel",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Fire Herb",
	"Ivy",
	"Sap Plant",
	"Woemill Wheat",
	"Gloamgrass Bud",
	"Cactus Flower",
	"Unknown",
	"Unknown",
	"Unknown",
	"Moon Grass",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Nulberry",
	"Dragonfell Berry",
	"Paintberry",
	"Fatty Tomato",
	"Heftcorn",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Blue Mushroom",
	"Mandragora",
	"Nitroshroom",
	"King Truffle",
	"Beauty Shroom",
	"Toadstool",
	"Stinkshroom",
	"Duskshroom",
	"Chillshroom",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Honey",
	"Mixed Honey",
	"Snakebee Larva",
	"Aged Honey",
	"Hakolo Honey",
	"Alcala Honey",
	"Loloska Honey",
	"Lamure Honey",
	"Terga Honey",
	"Honey Butter",
	"Unknown",
	"Unknown",
	"Unknown",
	"Bitterbug",
	"Godbug",
	"Flashbug",
	"Shiny Beetle",
	"Thunderbug",
	"Insect Husk",
	"Spicy Worm",
	"Ricebug",
	"King Scarab",
	"Rare Scarab",
	"Spider Web",
	"Carpenterbug",
	"Hercudrome",
	"Unknown",
	"Unknown",
	"Night Cryder Web",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Iron Ore",
	"Earth Crystal",
	"Pelagicite Ore",
	"Machalite Ore",
	"Dragonite Ore",
	"Yoldspar Ore",
	"Firestone",
	"Unknown",
	"Novacrystal",
	"Unknown",
	"Comet Salt",
	"Lightcrystal",
	"Unknown",
	"Carbalite Ore",
	"Fucium Ore",
	"Firecell Stone",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Sushifish",
	"Queen Shrimp",
	"Whetfish",
	"Sleepyfish",
	"Sharktuna",
	"Speartuna",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Raw Meat",
	"Unknown",
	"Quality Meat",
	"High-Quality Meat",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Wyvern Barbs",
	"Unknown",
	"Screamer Sac",
	"Unknown",
	"Poison Sac",
	"Toxin Sac",
	"Paralysis Sac",
	"Debilitation Sac",
	"Sleep Sac",
	"Coma Sac",
	"Blast Sac",
	"Explosion Sac",
	"Flame Sac",
	"Inferno Sac",
	"Aqua Sac",
	"Torrent Sac",
	"Electro Sac",
	"Thunder Sac",
	"Frost Sac",
	"Freezer Sac",
	"Whelp Core",
	"Dragon Core",
	"Wyvern Stone",
	"Wyvern Gem",
	"Larinoth Hide",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Rathian Shell",
	"Rathian Spike",
	"Rathian Plate",
	"Rathian Carapace",
	"Rathian Spike+",
	"Rathian Ruby",
	"Pink Rathian Shell",
	"Pink Rathian Thorn",
	"Pink Rathian Plate",
	"Pink Rathian Carapace",
	"Pink Rathian Spike+",
	"Pink Rathian Ruby",
	"G. Rathian Carapace",
	"G. Rathian Spike+",
	"Gold Rathian Ruby",
	"Rathalos Scale",
	"Rathalos Webbing",
	"Rathalos Plate",
	"Rathalos Scale+",
	"Rathalos Wing",
	"Rathalos Ruby",
	"Azure Rathalos Scale",
	"Azure Rathalos Web",
	"Azure Rathalos Plate",
	"Azure Rathalos Scale+",
	"Azure Rathalos Wing",
	"Azure Rathalos Ruby",
	"S. Rathalos Scale+",
	"S. Rathalos Wing",
	"S. Rathalos Ruby",
	"Kut-Ku Scale",
	"Kut-Ku Webbing",
	"Giant Beak",
	"Kut-Ku Scale+",
	"Kut-Ku Wing",
	"Splendid Beak",
	"Blue Kut-Ku Scale",
	"Blue Kut-Ku Shell",
	"Blue Kut-Ku Ear",
	"Blue Kut-Ku Scale+",
	"Blue Kut-Ku Carapace",
	"Blue Kut-Ku Ear+",
	"Rubbery Hide",
	"Gypceros Webbing",
	"Gypceros Head",
	"Rubbery Hide+",
	"Gypceros Wing",
	"Gypceros Hardhead",
	"Rubbery P. Hide",
	"P. Gypceros Web",
	"Rubbery P. Tail",
	"Rubbery P. Hide+",
	"P. Gypceros Wing",
	"Rubbery P. Tail+",
	"Tigrex Scale",
	"Tigrex Claw",
	"Tigrex Scalp",
	"Tigrex Scale+",
	"Tigrex Claw+",
	"Tigrex Maw",
	"Brute Tigrex Scale",
	"Brute Tigrex Claw",
	"Brute Tigrex Tail",
	"Brute Tigrex Scale+",
	"Brute Tigrex Claw+",
	"Brute Tigrex Tail+",
	"Molten Tigrex Scale+",
	"M. Tigrex Blastclaw",
	"Pulsating Blastheart",
	"Gendrome Hide",
	"Gendrome Fang",
	"Gendrome Head",
	"Gendrome Hide+",
	"Gendrome Fang+",
	"Gendrome Body",
	"Iodrome Hide",
	"Iodrome Violet Scale",
	"Iodrome Head",
	"Iodrome Hide+",
	"Iodrome Violet Scale+",
	"Iodrome Body",
	"Great Jaggi Hide",
	"Great Jaggi Claw",
	"King's Frill",
	"Great Jaggi Hide+",
	"Great Jaggi Claw+",
	"Great Jaggi Head",
	"Velocidrome Hide",
	"Velocidrome Claw",
	"Velocidrome Head",
	"Velocidrome Hide+",
	"Velocidrome Claw+",
	"Velocidrome Body",
	"Congalala Pelt",
	"Congalala Claw",
	"Vibrant Pelt",
	"Congalala Pelt+",
	"Congalala Claw+",
	"Vibrant Pelt+",
	"E. Congalala Pelt",
	"E. Congalala Claw",
	"E. Congalala Tail",
	"E. Congalala Pelt+",
	"E. Congalala Claw+",
	"E. Congalala Tail+",
	"Rajang Blackfur",
	"Rajang Horn",
	"Gold Rajang Pelt",
	"Rajang Ragehair",
	"Rajang Horn+",
	"Rajang Nerve",
	"Kecha Pelt",
	"Kecha Longbone",
	"Kecha Ear",
	"Kecha Pelt+",
	"Kecha Grandbone",
	"Kecha Ear+",
	"Zamtrios Hide",
	"Zamtrios Fin",
	"Zamtrios Tailblade",
	"Zamtrios Hide+",
	"Zamtrios Fin+",
	"Zamtrios Tailblade+",
	"Nerscylla Shell",
	"Nerscylla Chelicera",
	"Nerscylla Spike",
	"Nerscylla Carapace",
	"Nerscylla Shear",
	"Nerscylla Spike+",
	"Garuga Scale",
	"Garuga Ear",
	"Sharpened Beak",
	"Garuga Scale+",
	"Garuga Auricle",
	"Rejuvenated Beak",
	"Daora Carapace",
	"Daora Horn+",
	"Daora Gem",
	"Teostra Carapace",
	"Teostra Mane",
	"Teostra Gem",
	"Unknown",
	"Unknown",
	"Unknown",
	"Kirin Hide+",
	"Kirin Thundertail",
	"Kirin Azure Horn",
	"Unknown",
	"Unknown",
	"Unknown",
	"Kirin Blackhide+",
	"Kirin Frost Tail+",
	"Kirin Icehorn+",
	"Flabby Hide",
	"Flabby Webbing",
	"Pale Bone",
	"Pearl Hide",
	"Pearl Wing",
	"Pale Steak",
	"Alluring Hide",
	"Alluring Webbing",
	"Alluring Lips",
	"Alluring Tenderhide",
	"Alluring Wing",
	"Alluring Thicklips",
	"Basarios Shell",
	"Basarios Webbing",
	"Basarios Tears",
	"Basarios Carapace",
	"Basarios Wing",
	"Basarios Tearglands",
	"Ruby Basarios Shell",
	"R. Basarios Webbing",
	"Ruby Basarios Head",
	"R. Basarios Carapace",
	"Ruby Basarios Wing",
	"R. Basa Stonehead",
	"Gravios Shell",
	"Gravios Scalp",
	"Gravios Bone Marrow",
	"Gravios Carapace",
	"Gravios Jaw",
	"Gravios Medulla",
	"Black Gravios Shell",
	"Black Gravios Scalp",
	"Black Gravios Marrow",
	"B. Gravios Carapace",
	"Black Gravios Jaw",
	"B. Gravios Medulla",
	"Deviljho Scale",
	"Deviljho Fang",
	"Deviljho Talon",
	"Deviljho Blackscale",
	"Deviljho Tallfang",
	"Deviljho Gem",
	"Brach Shell",
	"Brach Hammer",
	"Brach Marrow",
	"Brach Carapace",
	"Brach Pounder",
	"Brach Gem",
	"Lagombi Pelt",
	"Lagombi Plastron",
	"Lagombi Ear",
	"Lagombi Pelt+",
	"Lagombi Plastron+",
	"Lagombi Ear+",
	"Zinogre Shell",
	"Zinogre Shockfur",
	"Zinogre Plate",
	"Zinogre Carapace",
	"Zinogre Electrofur",
	"Zinogre Jasper",
	"S. Zinogre Shell",
	"Stygian Zinogre Claw",
	"S. Zinogre Plate",
	"S. Zinogre Carapace",
	"S. Zinogre Claw+",
	"S. Zinogre Umbrage",
	"Fatalis Scale",
	"Fatalis Crust",
	"Fatalis Eye",
	"Seregios Slavescale",
	"Seregios Impaler",
	"Seregios Dissenter",
	"Ash Kecha Fur",
	"Ash Kecha Longbone",
	"Ash Kecha Ear",
	"Ash Kecha Thickfur",
	"Ash Kecha Grandbone",
	"Ash Kecha Ear+",
	"S. Nerscylla Shell",
	"S. Nerscylla Chel",
	"S. Nerscylla Claw",
	"S. Nerscylla Carapace",
	"S. Nerscylla Shear",
	"S. Nerscylla Claw+",
	"Diablos Shell",
	"Diablos Tail",
	"Twisted Horn",
	"Diablos Carapace",
	"Diablos Tail+",
	"Majestic Horn",
	"Black Diablos Shell",
	"Black Diablos Tail",
	"Twisted B. Diablos Horn",
	"B. Diablos Carapace",
	"Black Diablos Tail+",
	"Black Twisted Horn",
	"Monoblos Shell",
	"Monoblos Ridge",
	"Blood Red Horn",
	"Monoblos Carapace",
	"Monoblos Thoracic",
	"Scarlet Finehorn",
	"W. Monoblos Shell",
	"W. Monoblos Ridge",
	"W. Monoblos Horn",
	"W. Monoblos Carapace",
	"W. Monoblos Thorax",
	"Top-Grade Plated Horn",
	"Cephadrome Scale",
	"Cephadrome Fang",
	"Cephadrome Fin",
	"Cephadrome Scale+",
	"Cephadrome Fang+",
	"Cephadrome Fin+",
	"Daimyo Shell",
	"Daimyo Claw",
	"Daimyo Pearl",
	"Daimyo Carapace",
	"Daimyo Claw+",
	"Daimyo Pearl+",
	"Plum Daimyo Shell",
	"Plum Daimyo Claw",
	"Plum Daimyo Feeler",
	"Plum Daimyo Carapace",
	"Plum Daimyo Claw+",
	"Plum Daimyo Feeler+",
	"Great Baggi Hide",
	"Great Baggi Claw",
	"King's Crest",
	"Great Baggi Hide+",
	"Great Baggi Claw+",
	"Great Baggi Head",
	"Royal Ludroth Scale",
	"Royal Ludroth Tail",
	"Royal Ludroth Crest",
	"Royal Ludroth Scale+",
	"Royal Ludroth Tail+",
	"Royal Ludroth Crest+",
	"P. Ludroth Scale",
	"P. Ludroth Claw",
	"Plum Spongy Hide",
	"P. Ludroth Scale+",
	"P. Ludroth Claw+",
	"P. Spongy Hide+",
	"Barroth Shell",
	"Barroth Claw",
	"Barroth Scalp",
	"Barroth Carapace",
	"Barroth Claw+",
	"Barroth Scalp+",
	"Jade Barroth Shell",
	"Jade Barroth Claw",
	"Jade Barroth Scalp",
	"J. Barroth Carapace",
	"Jade Barroth Claw+",
	"Jade Barroth Scalp+",
	"Barioth Shell",
	"Barioth Spike",
	"Amber Tusks",
	"Barioth Carapace",
	"Barioth Spike+",
	"Amber Tusks+",
	"Sand Barioth Shell",
	"Sand Barioth Pelt",
	"Indigo Tusks",
	"S. Barioth Carapace",
	"Sand Barioth Pelt+",
	"Indigo Tusks+",
	"Qurupeco Scale",
	"Qurupeco Feather",
	"Strange Beak",
	"Qurupeco Scale+",
	"Qurupeco Wing",
	"Wonderful Beak",
	"Crimson Peco Scale",
	"Crimson Peco Feather",
	"Flamboyant Quill",
	"Crimson Peco Scale+",
	"Crimson Peco Wing",
	"Peco Pipes",
	"Bulldrome Hide",
	"Bulldrome Tusk",
	"Bulldrome Bone",
	"Bulldrome Hide+",
	"Twisted Bulldrome Tusk",
	"Bulldrome Scalp",
	"Arzuros Pelt",
	"Arzuros Shell",
	"Arzuros Brace",
	"Arzuros Pelt+",
	"Arzuros Carapace",
	"Arzuros Brace+",
	"Uragaan Scale",
	"Uragaan Shell",
	"Uragaan Jaw",
	"Uragaan Scale+",
	"Uragaan Carapace",
	"Uragaan Ruby",
	"Lagiacrus Scale",
	"Lagiacrus Horn",
	"Lagiacrus Shockshell",
	"Lagiacrus Scale+",
	"Lagiacrus Horn+",
	"Lagi Shockshell+",
	"Ivory Lagi Scale",
	"Ivory Lagi Horn",
	"I. Lagi Shockshell",
	"Ivory Lagi Scale+",
	"Ivory Lagi Horn+",
	"I. Lagi Shockshell+",
	"Agnaktor Shell",
	"Agnaktor Claw",
	"Agnaktor Beak",
	"Agnaktor Carapace",
	"Agnaktor Claw+",
	"Agnaktor Beak+",
	"G. Agnak Shell",
	"G. Agnak Claw",
	"G. Agnak Beak",
	"G. Agnak Crpace",
	"G. Agnak Claw+",
	"G. Agnak Beak+",
	"Plesioth Scale",
	"Plesioth Fang",
	"Plesioth Fin",
	"Plesioth Scale+",
	"Plesioth Fang+",
	"Plesioth Fin+",
	"Green Plesioth Scale",
	"Green Plesioth Fang",
	"Green Plesioth Fin",
	"G. Plesioth Scale+",
	"Green Plesioth Fang+",
	"Green Plesioth Fin+",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Nargacuga Scale",
	"Nargacuga Blackfur",
	"Nargacuga Cutwing",
	"Nargacuga Scale+",
	"Nargacuga Pelt+",
	"Nargacuga Razor",
	"Green Narga Scale",
	"G. Narga Mottlefur",
	"Green Narga Cutwing",
	"Green Narga Scale+",
	"G. Narga Mottlefur+",
	"Green Narga Cutwing+",
	"Unknown",
	"Monster Bone S",
	"Monster Bone M",
	"Brute Bone S",
	"Monster Fluid",
	"Zamite Scale",
	"Slagtoth Hide",
	"Aptonoth Tail",
	"Popo Pelt",
	"Ludroth Pelt",
	"Conga Pelt",
	"Bullfango Pelt",
	"Cephalos Scale",
	"Hermitaur Shell",
	"Bnahabra Shell",
	"Vespoid Wing",
	"Konchu Shell",
	"Ioprey Scale",
	"Genprey Scale",
	"Jaggi Scale",
	"Baggi Scale",
	"Velociprey Scale",
	"Remobra Hide",
	"Shaka Treasure",
	"Altaroth Stomach",
	"Fine Stomach",
	"Uroktor Scale",
	"Pawprint Stamp",
	"Gargwa Feather",
	"Monster Bone L",
	"Monster Bone+",
	"Dragonbone Relic",
	"Stoutbone",
	"Kelbi Horn",
	"Apceros Shell",
	"Zamite Scale+",
	"Herbivore Bone",
	"Ludroth Pelt+",
	"Fanged Beast Fur",
	"Cephalos Scale+",
	"Hermitaur Shell+",
	"Neopteron Shell",
	"Bird Wyvern Scale+",
	"Remobra Hide+",
	"Shaka Treasure+",
	"Luminous Stomach",
	"Uroktor Scale+",
	"Barrel Lid",
	"Blue Gargwa Feather",
	"Shocking Extract",
	"Shocking Jelly",
	"Dragonbug Juice",
	"Dragonbug Jelly",
	"Monster Broth",
	"Elder Dragon Blood",
	"Brute Bone M",
	"Brute Bone L",
	"Dreadqueen Scale+",
	"Dreadqueen Carapace",
	"Dreadqueen Ruby",
	"Dreadking Scale+",
	"Dreadking Fellwing",
	"Dreadking Ruby",
	"Grill",
	"Iron Pickaxe",
	"Bug Net",
	"Fishing Rod",
	"Rider's Notes",
	"Monsterpedia",
	"Bronze License",
	"Silver License",
	"Gold License",
	"Platinum License",
	"Unidentified Shard",
	"Ancient Relic",
	"Important Letter",
	"Crude Felyne Carving",
	"Good Times Felvine",
	"Traditional Charm",
	"Unknown",
	"Downy Crake",
	"Gargwa Statue",
	"Pirate Treasure",
	"Expedition Ticket (N)",
	"Expedition Ticket (R)",
	"Expedition Ticket (SR)",
	"Clerk's Letter",
	"Palamute Ticket (N)",
	"Palamute Ticket (R)",
	"Palamute Ticket (SR)",
	"Unknown",
	"Windmill Parts",
	"Rathalos Egg",
	"Kayna's Recipe",
	"Tracking Basics",
	"Mega Potions",
	"Hunter's Life: Fall",
	"Hunter's Life: Winter",
	"Healer's Comp V.1",
	"Healer's Comp V.3",
	"Warm and Healthy",
	"Hunter's Life: Summer",
	"Cool and Healthy",
	"Group Healing 101",
	"Group Healing Int",
	"Positivity Pills",
	"Healer's Comp V.4",
	"Essence Vitale",
	"Group Healing Adv",
	"Healer's Comp V.2",
	"Perfect Vision",
	"Trendsetter: Scents",
	"Deep Clean",
	"Taste of Home",
	"Alwin's Specialty",
	"Family Favorite",
	"Sweet Secret",
	"Culinary Traditions",
	"Knifepedia: Poison",
	"Knifepedia: Paralysis",
	"Knifepedia: Sleep",
	"Pitfall Surprise",
	"Shocking Surprise",
	"Tranquil Surprise",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Need a Boost?",
	"Hunter's Life: Spring",
	"Boom Boom Book",
	"Big Boom Boom Book",
	"Unknown",
	"Unknown",
	"Flash Bomb How-To",
	"Boom Boom Bang Book",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"S&S Basics: Defense",
	"S&S: Counter",
	"Great Sword: Guard",
	"Great Sword Moves 1",
	"Great Sword Moves 2",
	"Great Sword Moves 3",
	"Great Sword Moves 4",
	"Hammer: Evasion",
	"Hammer: Surge",
	"H. Horn: A. Evasion",
	"H. Horn: N. Poison",
	"H. Horn: N. Sleep",
	"H. Horn: N. Para.",
	"H. Horn: N. Ailments",
	"H. Horn: Iron Def.",
	"H. Horn: Blast",
	"H. Horn: Saver",
	"H. Horn: Awakening",
	"H. Horn: Charge",
	"H. Horn: Berserk",
	"H. Horn: Kinship",
	"H. Horn: Bloodsuck",
	"H. Horn: Soothing",
	"H. Horn: Healing",
	"H. Horn: Mettle",
	"H. Horn: Evasion",
	"Gunlance: Guard",
	"Gunlance: Protect",
	"Gunlance: Seal",
	"Gunlance: Wyv. Fire",
	"Gunlance: Shelling",
	"Gunlance: Wyrmstake",
	"Gunlance: Full Burst",
	"Bow: Evasion",
	"Bow Tech: Arc Shot",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Red Hero Outfit",
	"Blue Hero Outfit",
	"Green Hero Outfit",
	"White Flu Mask",
	"Black Flu Mask",
	"Pink Flu Mask",
	"R Cheerleader Outfit",
	"G Cheerleader Outfit",
	"B Cheerleader Outfit",
	"Wanderer's Outfit",
	"Eyepatch Outfit",
	"Bandaged Outfit",
	"Naviljho Outfit",
	"King's Outfit",
	"Azure King's Outfit",
	"Silver King's Outfit",
	"Ruin King's Outfit",
	"Numbers Outfit",
	"Heart-Shaped Glasses",
	"Purrty-Eye Frames",
	"Mahana Headband",
	"Rutoh Scarf",
	"Kuan Cap",
	"Lulucion Hat",
	"A Nua Look",
	"Felyne Straw Hat",
	"Pawesome Outfit",
	"Moonblessed Outfit",
	"Pukei-Pukei Costume",
	"Nergigante Costume",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Hakum Rider Outfit",
	"Kyle's & Ena's Outfit",
	"Red's Outfit",
	"Mahana Outfit",
	"Tsukino Onesie",
	"Razewing Armor Alpha",
	"Kamura Garb",
	"Razewing Armor Beta",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"Unknown",
	"Adventure Buddies 2",
	"Adventure Buddies 3",
	"Unknown",
	"@",
	"@",
	"@",
	"@",
	"@",
	"Unknown",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Mint Leaf",
	"Stink Scrub",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Heart Churro",
	"Armor Sphere M",
	"Armor Sphere L",
	"Weapon Sphere S",
	"Weapon Sphere M",
	"Weapon Sphere L",
	"Grimclaw Scale+",
	"Grimclaw Carapace",
	"Grimclaw Talon+",
	"Kushala Daora Shell",
	"Kushala Daora Horn",
	"Kushala Daora Claw",
	"Thunderlord Carapace",
	"Thunderlord Electrofur",
	"Thunderlord Horn+",
	"Seregios Sharpscale",
	"Seregios Bladehorn",
	"Seregios Claw",
	"Bloodbath Cortex",
	"Bloodbath Chine",
	"Bloodbath Grimhorn",
	"Silverwind Scale+",
	"Silverwind Blackfur+",
	"Silverwind Razor",
	"Seltas Shell",
	"Seltas Wing",
	"Seltas Horn",
	"Seltas Carapace",
	"Seltas Innerwing",
	"Seltas Sharphorn",
	"Seltas Queen Shell",
	"Seltas Queen Claw",
	"Seltas Queen Fluid",
	"S. Queen Carapace",
	"Seltas Queen Claw+",
	"Seltas Queen Fluid+",
	"Desert Queen Shell",
	"Desert Queen Claw",
	"Desert Queen Pleura",
	"Desert Queen Jaw",
	"Desert Queen Tail",
	"Desert Queen Hardclaw",
	"Kulu-Ya-Ku Hide",
	"Kulu-Ya-Ku Beak",
	"Kulu-Ya-Ku Plume",
	"Kulu-Ya-Ku Hide+",
	"Kulu-Ya-Ku Beak+",
	"Kulu-Ya-Ku Plume+",
	"Pukei-Pukei Scale",
	"Pukei-Pukei Sac",
	"Pukei-Pukei Tail",
	"Pukei-Pukei Scale+",
	"Pukei-Pukei Wing",
	"Pukei-Pukei Sac+",
	"Gammoth Hide",
	"Gammoth Shell",
	"Gammoth Tusk",
	"Gammoth Pelt",
	"Gammoth Shell+",
	"Gammoth Tusk+",
	"Elderfrost Pelt",
	"Elderfrost Cortex",
	"Elderfrost Trunkspine",
	"Tetsucabra Scale",
	"Paddock Oil",
	"Tetsucabra Tusks",
	"Tetsucabra Scale+",
	"Paddock Oil+",
	"Tetsucabra Tusks+",
	"Mizutsune Purplefur",
	"Mizutsune Fin",
	"Mizutsune Plate",
	"Mizutsune Purplefur+",
	"Mizutsune Fin+",
	"Mizutsune Water Orb",
	"Soulseer Shard",
	"Soulseer Purplehide",
	"Soulseer Tail",
	"Duramboros Shell",
	"Duramboros Horn",
	"Duramboros Tailbone",
	"Duramboros Shell+",
	"Duramboros Horn+",
	"Duramboros Sacrum",
	"Glavenus Fang",
	"Glavenus Hellshell",
	"Glavenus Plate",
	"Glavenus Fang+",
	"Glavenus Hellshell+",
	"Glavenus Flamegem",
	"Hellblade Scale+",
	"Hellblade Carapace",
	"Hellblade Powder",
	"Anjanath Scale",
	"Anjanath Nosebone",
	"Anjanath Fang",
	"Anjanath Scale+",
	"Anjanath Nosebone+",
	"Anjanath Fang+",
	"Astalos Scale",
	"Astalos Crest",
	"Astalos Plate",
	"Astalos Scale+",
	"Astalos Crest+",
	"Astalos Boltgem",
	"Boltreaver Shard",
	"Heavy Boltreaver Shell",
	"Boltreaver Electric Barb",
	"Paolumu Pelt",
	"Paolumu Webbing",
	"Paolumu Shell",
	"Paolumu Pelt+",
	"Paolumu Wing",
	"Paolumu Carapace+",
	"Legiana Claw",
	"Legiana Webbing",
	"Legiana Plate",
	"Legiana Claw+",
	"Legiana Wing",
	"Legiana Gem",
	"Bazelgeuse Scale",
	"Bazelgeuse Shell",
	"Bazelgeuse Claw",
	"Bazelgeuse Wing",
	"Bazelgeuse Fuse",
	"Bazelgeuse Gem",
	"Tobi-Kadachi Pelt",
	"Tobi-Kadachi Claw",
	"Tobi-Kadachi Electrode",
	"Tobi-Kadachi Pelt+",
	"Tobi-Kadachi Claw+",
	"Tobi-Kadachi Electrode+",
	"Nergigante Shell",
	"Nergigante Tail",
	"Nergi Regrowth Plate",
	"Nergigante Talon",
	"Nergigante Horn+",
	"Nergigante Gem",
	"Kulve Taroth Golden Scale",
	"Kulve Taroth Golden Shell",
	"K. T. Golden Spiralhorn",
	"F. Anjanath Scale",
	"F. Anjanath Pelt",
	"F. Anjanath Fang",
	"F. Anjanath Lash",
	"F. Anjanath Nosebone",
	"F. Anjanath Mantle",
	"Velkhana Shell",
	"Velkhana Wing",
	"Velkhana Claw",
	"Velkhana Lash",
	"Velkhana Crownhorn",
	"Velkhana Crystal",
	"Red's Notes #1",
	"Red's Notes #2",
	"Red's Notes #3",
	"Red's Notes #4",
	"Red's Notes #5",
	"Red's Notes #6",
	"Red's Notes #7",
	"Unknown",
	"Red's Notes #8",
	"Unknown",
	"Red's Notes #9",
	"Unknown",
	"Unknown",
	"White Dress",
	"Tropical Dress",
	"Kuan Coat",
	"Ancient Raiment",
	"Felyne Shelter Garb",
	"Cheerleader (Blue)",
	"Cheerleader (Orange)",
	"Cheerleader (Pink)",
	"Blue Traveling Gear",
	"Pink Traveling Gear",
	"Kamura Maiden Outfit",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"Downy Duds",
	"Kulu-Ya-Ku Costume",
	"Legiana Costume",
	"Paolumu Costume",
	"Anjanath Costume",
	"Fulgur Anja Costume",
	"Velkhana Costume",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"Character Edit Ticket",
	"Character Edit Ticket",
	"Character Edit Ticket",
	"Character Edit Ticket",
	"Character Edit Ticket",
	"Character Edit Ticket",
	"Character Edit Ticket",
	"Character Edit Ticket",
	"Character Edit Ticket",
	"Character Edit Ticket",
	"Character Edit Ticket",
	"Character Edit Ticket",
	"Character Edit Ticket",
	"Character Edit Ticket",
	"Character Edit Ticket",
	"Character Edit Ticket",
	"Character Edit Ticket",
	"Character Edit Ticket",
	"Character Edit Ticket",
	"Character Edit Ticket",
	"@",
	"@",
	"@",
	"@",
	"@",
	"Hunter Sticker Set",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"Spiky Nergal",
	"Shaggy Legiana",
	"Lumu Afro",
	"Mizutsune Braid",
	"Mohawk Kulu",
	"Mohawk Zuros",
	"Shaggy Narga",
	"Spiky Rathalos",
	"Conga Cone",
	"Barroth Pompadour",
	"Brachy Pompadour",
	"Royal Rolls",
	"Funky Kut-Ku",
	"Kelbi Braid",
	"Spiky Rathian",
	"Barioth Braids",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"@",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
};
